logging:
  path: /usr/log/exam/

spring:
  redis:
    host: 192.168.0.96
  datasource:
    url: jdbc:mysql://192.168.0.69:3306/video_mangage_db?useSSL=false&useUnicode=true&serverTimezone=UTC&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
